#! /usr/bin/env python
# genvid

import os
import sys
from libtovid.opts import Option, OptionDict
from libtovid.flipbook import Flipbook
from libtovid.effect import Movement, Fade, Colorfade, Spectrum, Scale
from libtovid.layer import Background, Text, Thumb, ThumbGrid, VideoClip

# Valid command-line options to this script
options = [\
    Option('out', 'FILE', None,
           """Use the given output file prefix (.m2v added automatically)"""),
    Option('frames', 'NUM', 30,
           """Generate NUM frames total"""),
    Option('bgcolor', 'COLOR', 'black',
           """Use the given background color"""),
    Option('title', 'TEXT', '',
           """Display the given title text"""),
    Option('thumbs', 'FILE[,FILE...]', [],
           """Create thumbnail images of the given list of images""")
    ]

# Main function
if __name__ == '__main__':
    # Fill useropts with default values
    useropts = OptionDict(options)

    # Print usage notes if not enough arguments were given
    if len(sys.argv) < 3:
        print "Usage: genvid [OPTIONS] -out FILE"
        print "where OPTIONS may be:"
        print useropts.usage()
        sys.exit(1)
    # Override with any options provided on the command-line
    else:
        useropts.override(sys.argv[1:])

    # Make sure output prefix was provided
    if not useropts['out']:
        print "Please provide an output prefix with -out"
        sys.exit(1)

    # TODO: PAL/NTSC frame size
    flip = Flipbook(useropts['frames'])

    # Background color
    bgd = Background(color=useropts['bgcolor'])
    flip.add(bgd)

    # Title string
    if useropts['title'] is not '':
        # TODO: Centered text! (gravity)
        title = Text(useropts['title'], fontsize=30)
        flip.add(title, (280, 80))
    # Thumbnails
    if useropts['thumbs'] is not []:
        thumbs = ThumbGrid(useropts['thumbs'], (600, 400))
        flip.add(thumbs, (60, 40))

    flip.render_video(useropts['out'])
