#! /usr/bin/env python
# tovidgui

"""A wxPython frontend for the tovid suite.
"""

# tovid GUI
# ===============
# A wxPython frontend for the tovid suite
#
# Project homepage: http://tovid.wikia.com
#
# Copyright (C) 2005-2010
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. Or see:
#
#     http://www.gnu.org/licenses/gpl.txt

import sys
import traceback

# wxversion (wxpython 2.6) is required
try:
    import wxversion
except ImportError:
    traceback.print_exc()
    print("There was an error importing the 'wx' libraries. The above")
    print("output should help you find what went wrong. Re-installing")
    print("wxPython 2.6 (or upgrading from wxPython 2.4 to 2.6) may")
    print("help. Consult the tovid homepage (http://tovid.wikia.com/)")
    print("for further assistance.")
    print("Sorry, 'tovidgui' will not work.")
    sys.exit()

# Use wx version 2.6 or 2.8
_allowed_versions = [
    '2.6-unicode',
    '2.8-unicode',
    '2.6-gtk-unicode',
    '2.8-gtk-unicode']
try:
    wxversion.select(_allowed_versions)
except wxversion.VersionError:
    print("tovidgui requires wxPython 2.6 or 2.8.")
    print("Please install or upgrade wxPython.")
    sys.exit()

import wx
from libtovid.gui.frames import TovidFrame

TovidGUI = wx.PySimpleApp()
#frame = MiniEditorFrame(None, wx.ID_ANY, "tovid GUI")
frame = TovidFrame(None, wx.ID_ANY, "tovid GUI - simple menus using 'makemenu'")
frame.Show(True)
TovidGUI.MainLoop()
