#! /usr/bin/env python
# pyidvid

import sys
import os

import logging
from libtovid.filetypes import MediaFile

log = logging.getLogger('libtovid')
log.setLevel(logging.DEBUG)
log.addHandler(logging.StreamHandler(sys.stdout))

if __name__ == '__main__':
    # If no arguments were provided, print usage notes
    if len(sys.argv) == 1:
        print "Usage: %s FILE" % sys.argv[0]
    else:
        for file in sys.argv[1:]:
            print "Identifying file: %s" % sys.argv[1]
            infile = MediaFile(file)
            infile.display()

