#! /usr/bin/env python2.4
# pymakemenu

# Generate an (S)VCD/DVD menu MPEG
# (to replace the 'makemenu' shell script)

import sys, libtovid
from libtovid.menu import Menu
from libtovid.project import Project

if __name__ == '__main__':
    """Parse the provided command-line arguments as a Menu element."""

    # If no arguments were provided, print usage notes

    # TODO: Proper argument verification
    if len(sys.argv) < 3:
        print 'Usage: pymakemenu [options] -out NAME'
        print 'Where [options] may be any of the following:'
        print libtovid.tdl.usage('Menu')
        print 'Please provide an output name (-out).'
        sys.exit()

    else:
        print "pymakemenu"
        args = sys.argv[1:]
        menu = Menu(args)
        menu.generate()
