#! /usr/bin/env python2.4
# pymakexml

__doc__ = \
"""Generate vcdimager/dvdauthor XML for an (S)VCD/DVD disc (to replace the
'makexml' shell script).
"""

import sys

import libtovid

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print "Usage: pymakexml [options] vid1.mpg vid2.mpg ... -out NAME"
        print "See the 'makexml' manual page for more details."
        sys.exit()

    # Create a TDL disc element definition using the
    # provided command-line options

    # Insert a dummy element/name declaration
    sys.argv.insert(0, 'Disc')
    sys.argv.insert(1, '"FOO DISC"')

    par = libtovid.tdl.Parser()
    elems = par.parse_args(sys.argv)
    print "Parsed Disc element:"
    print elems[0].to_string()
    print "Generating disc XML..."
    elems[0].generate()
    

