#! /usr/bin/env python2.4

# pytovid
# Convert a video into an (S)VCD/DVD-compliant MPEG
# (to replace the 'tovid' shell script)

import sys

import libtovid
from libtovid.video import Video
from libtovid import tdl

if __name__ == '__main__':
    """Create a Video element from the provided command-line options,
    and generate it using the Video module."""
    
    # TODO: Fix ugly parsing hack here (i.e., find a way to properly verify
    # arguments before proceeding)
    if len(sys.argv) < 5:
        print 'Usage: pytovid [options] -in FILE -out NAME'
        print 'Where [options] may be any of the following:'
        print tdl.usage('Video')
        print 'Please provide an input file (-in) and output name (-out).'
        sys.exit()

    # Create a TDL video element definition using the
    # provided command-line options

    args = sys.argv[1:]

    # Insert a dummy element/name declaration
    args.insert(0, 'Video')
    args.insert(1, '"FOO VIDEO"')

    par = tdl.Parser()
    elems = par.parse_args(args)
    print "Parsed Video element:"
    print elems[0].to_string()
    print "Generating video..."
    Video.generate(elems[0])

