#!/usr/bin/env python

import sys
import Tkinter as tk
from libtovid.guis.helpers import SetChapters
from os import path

if len(sys.argv) < 2:
    print("Usage: set_chapters.py video")
    exit()
video = sys.argv[1]
if not path.exists(video):
    print('Error: %s does not exist' %video)
    exit()

root = tk.Tk()
root.variable = tk.StringVar()
app = SetChapters(root, '-menu', 'Mplayer')
app.pack()
app.run(video)

root.mainloop()

