#! /usr/bin/env python
# todraw

"""A simple command-based paint program (and later, an interactive shell).
"""

try:
    from Tkinter import *
    from tkFileDialog import *
    from tkMessageBox import *
except:
    import traceback
    traceback.print_exc()
    print "Could not import Tkinter. You may need to do the following:"
    print "  Debian: Install 'python-tk'"
    print "  Gentoo: Add 'tcltk' to python USE flags"
    print "  Fedora: Install 'tkinter'"
    sys.exit()

from PIL import Image, ImageTk


class Application(Frame):
    def __init__(self, master=None, files=None, width=640, height=480):
        Frame.__init__(self, master, width=width, height=height)
        print "todraw application started, press 'q' or Escape to quit"
        print "Press the right arrow key to view the next image"
        self.width = width
        self.height = height
        self.grid()
        self.files = files or []
        self.lblImage = None
        self.setImage(files.pop(0))
        self.bind_all("<q>", self.onQuit)
        self.bind_all("<Escape>", self.onQuit)
        self.bind_all("<Right>", self.onNext)

    def onQuit(self, evt):
        print "Quitting todraw"
        sys.exit(0)
    
    def onNext(self, evt):
        """Load and display the next image file."""
        if self.files:
            self.setImage(self.files.pop(0))
        else:
            print "No more images to display"
        
    def setImage(self, filename):
        """Display the given image in the application window.
        """
        print "Displaying:", filename
        # Open the image and resize it
        image = Image.open(filename)
        image = image.resize((self.width, self.height))
        self.photo = ImageTk.PhotoImage(image, (self.width, self.height))
        # Create an pack a Label to hold the image
        if self.lblImage:
            self.lblImage.pack_forget()
        self.lblImage = Label(self, image=self.photo)
        self.lblImage.pack()


### --------------------------------------------------------------------
### Entry point
### --------------------------------------------------------------------
root = Tk()
if __name__ == '__main__':
    import sys
    if len(sys.argv) < 2:
        print "Displays a slideshow of the given images"
        print "Usage: todraw FILE [FILE ...]"
        exit(1)
    file = sys.argv[1:]
    root.title("todraw")
    app = Application(root, file)
    root.mainloop()
