#! /usr/bin/env python

# tovid GUI
# ===============
# A wxPython frontend for the tovid suite
#
# Project homepage: http://tovid.org/
#
# This software is licensed under the GNU General Public License
# For the full text of the GNU GPL, see:
#
#   http://www.gnu.org/copyleft/gpl.html
#
# No guarantees of any kind are associated with use of this software.
#

import sys

# Try to import wx; print error if it's unavailable
try:
    import wx
except ImportError:
    print "Python cannot find the 'wx' library. You may need to install or"
    print "upgrade wxPython 2.6.x."
    sys.exit()

from libtovid.gui.frames import MainFrame

TovidGUI = wx.PySimpleApp()
#frame = TovidFrame(None, wx.ID_ANY, "tovid GUI")
#frame = MiniEditorFrame(None, wx.ID_ANY, "tovid GUI")
frame = MainFrame(None, wx.ID_ANY, "tovid GUI")
frame.Show(True)
TovidGUI.MainLoop()
