#! /usr/bin/env python2.4

# tovid GUI
# ===============
# A wxPython frontend for the tovid suite
#
# Project homepage: http://tovid.org/
#
# This software is licensed under the GNU General Public License
# For the full text of the GNU GPL, see:
#
#   http://www.gnu.org/copyleft/gpl.html
#
# No guarantees of any kind are associated with use of this software.
#

import sys
import traceback

# Try to import wx; print error if it's unavailable
try:
    import wx
except ImportError:
    traceback.print_exc()
    print "Python can't find the 'wx' libraries. Here's where it looked:"
    for dir in sys.path[1:]:
        print "  " + dir
    print "You may need to install or upgrade wxPython 2.6.x [wxpython.org]."
    print "Sorry, 'tovidgui' will not work."
    sys.exit()

from libtovid.gui.frames import MainFrame

TovidGUI = wx.PySimpleApp()
#frame = TovidFrame(None, wx.ID_ANY, "tovid GUI")
#frame = MiniEditorFrame(None, wx.ID_ANY, "tovid GUI")
frame = MainFrame(None, wx.ID_ANY, "tovid GUI")
frame.Show(True)
TovidGUI.MainLoop()
