#! /usr/bin/env python

import sys
from libtovid import cli

def rungui(gui):
    cmd = cli.Command(gui)
    cmd.run()

if __name__ == '__main__':
    if len(sys.argv) < 2 or not \
      sys.argv[1] in ('-s', 'simple', '-f', 'fancy'):
        print("Usage: tovidgui simple|-s fancy|-f")
        sys.exit(1)

    if sys.argv[1] in ('-s', 'simple'):
        gui = 'makemenugui'
    elif sys.argv[1] in ('-f', 'fancy'):
        gui = 'todiscgui' 

    rungui(gui)
