#! /usr/bin/env python
# toyoutube

"""Convert video files to the format preferred by YouTube."""

import sys
from libtovid.opts import parse
from libtovid.cli import Command

def convert(infile, outfile):
    cmd = Command('ffmpeg')
    cmd.add('-i', infile,
            '-acodec', 'libmp3lame',
            '-ar', 44100,
            '-vcodec', 'libxvid',
            '-r', 30,
            '-ab', '64k',
            '-s', '320x240',
            '-b', '500k',
            '-y',
            outfile)
    cmd.run()

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print "Usage: toyoutube -in FILE -out FILE"
        sys.exit(1)

    options = parse(sys.argv[1:])

    convert(options['in'], options['out'])
