#! /bin/sh

USER="wapcaplet"
DEST="shell.berlios.de:/home/groups/tovid/htdocs"

if test $# -lt 1; then
    echo "Usage: $0 DIR"
    echo "Where DIR is a directory to upload."
    exit 1
fi

DIR=$1

echo "Uploading $DIR"
pushd $DIR
scp *.html *.css "$USER@$DEST/$DIR"
popd

