.TH "tovid manual" 1 "" ""


.P
\fIThis document was last edited on Wednesday, 15 February 2006.\fR

.SS Name
.P
tovid: Convert video to (S)VCD/DVD format

.SS Description
.P
tovid converts arbitrary video files into (S)VCD/DVD\-compliant
MPEG format, suitable for burning to CD/DVD\-R for playback on a
standalone DVD player.

.SS Usage
.P
\fBtovid\fR [ \fIOPTIONS\fR ] \fB\-in\fR \fIINFILE\fR \fB\-out\fR \fIOUTPREFIX\fR

.P
Where \fIINFILE\fR is any multimedia video file, and \fIOUTPREFIX\fR is what
you want to call the output file, minus the file extension. \fIOPTIONS\fR
are additional customizations, described below.

.P
By default, you will (hopefully) end up with an NTSC DVD\-compliant
MPEG\-2 video file; if you burn this file to a DVD\-R, it should be
playable on most DVD players.

.P
For example:

.TP
tovid \-in foo.avi \-out foo_encoded
Convert 'foo.avi' to NTSC DVD format, saving to 'foo_encoded.mpg'.

.TP
tovid \-pal \-vcd foo.avi \-out foo_encoded
Convert 'foo.avi' to PAL VCD format, saving to 'foo_encoded.mpg'.

.SS Basic options
.TP
\fB\-v\fR, \fB\-version\fR
Print tovid version number only

.SS Television standards
.TP
\fB\-ntsc\fR
NTSC format video (USA, Americas) (default)
.TP
\fB\-ntscfilm\fR
NTSC\-film format video
.TP
\fB\-pal\fR
PAL format video (Europe and others)

.SS Formats
.P
Standard formats, should be playable in most DVD players:

.TP
\fB\-dvd\fR
(720x480 NTSC, 720x576 PAL) DVD\-compatible output (default)
.TP
\fB\-half\-dvd\fR
(352x480 NTSC, 352x576 PAL) Half\-D1\-compatible output
.TP
\fB\-svcd\fR
(480x480 NTSC, 480x576 PAL) Super VideoCD\-compatible output
.TP
\fB\-dvd\-vcd\fR
(352x240 NTSC, 352x288 PAL) VCD\-on\-DVD output
.TP
\fB\-vcd\fR
(352x240 NTSC, 352x288 PAL) VideoCD\-compatible output

.P
Non\-standard formats, playable in some DVD players:

.TP
\fB\-kvcdx3\fR/\fB\-kvcd\fR
(528x480 NTSC, 520x576 PAL) KVCDx3 long\-playing VCD
.TP
\fB\-kvcdx3a\fR/\fB\-ksvcd\fR
(544x480 NTSC, 544x576 PAL) KVCDx3A long\-playing VCD
.TP
\fB\-kdvd\fR
(720x480 NTSC, 720x576 PAL) KDVD long\-playing DVD

.SS Advanced options
.SS Aspect ratios
.P
tovid automatically determines aspect ratio of the input video by playing it in
mplayer. If your video plays with correct aspect in mplayer, you should not
need to override the default tovid behavior.

.P
If mplayer does not play your video with correct aspect, you may provide an
explicit aspect ratio in one of several ways:

.TP
\fB\-full\fR
Same as \fB\-aspect 4:3\fR
.TP
\fB\-wide\fR
Same as \fB\-aspect 16:9\fR
.TP
\fB\-panavision\fR
Same as \fB\-aspect 235:100\fR
.TP
\fB\-aspect\fR \fIWIDTH\fR\fB:\fR\fIHEIGHT\fR
Custom aspect, where \fIWIDTH\fR and \fIHEIGHT\fR are integers.

.P
NOTE: This is the INPUT aspect ratio. tovid chooses an optimal output aspect
ratio for the selected disc format (VCD, DVD, etc.) and does the appropriate
letterboxing or anamorphic scaling.

.SS Video stream options
.TP
\fB\-quality\fR \fINUM\fR (EXPERIMENTAL)
Desired output quality, on a scale of 1 to 10, with 10 giving the best
quality at the expense of a larger output file. Output size can vary by
approximately a factor of 4 (that is, \-quality 1 output can be 25% the size
of \-quality 10 output). Your results may vary.

At present, this option affects both output bitrate and quantization (but
may, in the future, affect other quality/size\-related attributes). Use
\-vbitrate if you want to explicitly provide a maximium bitrate.

.TP
\fB\-vbitrate\fR \fINUM\fR
Maximum bitrate to use for video (in kbits/sec). Must be within allowable
limits for the given format. Overrides default values. Ignored for VCD.

.TP
\fB\-interlaced\fR (EXPERIMENTAL)
Do interlaced encoding of the input video. Use this option if your video is
interlaced, and you want to preserve as much picture quality as possible.
Ignored for VCD.

.TP
\fB\-deinterlace\fR (DEPRECATED)
Use this option if your source video is interlaced. You can usually tell if
you can see a bunch of horizontal lines when you pause the video during
playback. If you have recorded a video from TV or your VCR, it may be
interlaced. Use this option to convert to progressive (non\-interlaced)
video. This option is DEPRECATED, and will probably be ditched in favor of
interlaced encoding, which is better in almost every way.

.TP
\fB\-subtitles\fR \fIFILE\fR
Get subtitles from \fIFILE\fR and encode them into the video.  WARNING: This
hard\-codes the subtitles into the video, and you cannot turn them off while
viewing the video. By default, no subtitles are loaded. If your video is
already compliant with the chosen output format, it will be re\-encoded to
include the subtitles.

.TP
\fB\-type\fR {live|animation|bw}
Optimize video encoding for different kinds of video. Use 'live' (default)
for live\-action video, use 'animation' for cartoons or anime, and 'bw' for
black\-and\-white video.  This option currently only has an effect with
KVCD/KSVCD output formats; other formats may support this in the future.

.TP
\fB\-safe\fR \fIPERCENT\fR
Fit the video within a safe area defined by \fIPERCENT\fR. For example,
"\-safe 90%" will scale the video to 90% of the width/height of the output
resolution, and pad the edges with a black border. Use this if some of the
picture is cut off when played on your TV.  The percent sign is optional.

.TP
\fB\-filters\fR {none,denoise,contrast,all} (default none)
Apply post\-processing filters to enhance the video. If your input video is
very high quality, use 'none'. If your input video is grainy, use
'denoise'; if it looks washed out or faded, use 'contrast'. You can use
multiple filters separated by commas. To apply all filters, use 'all'.

.TP
\fB\-fps\fR \fIRATIO\fR
Force input video to be interpreted as \fIRATIO\fR frames per second.  May be
necessary for some ASF, MOV, or other videos. \fIRATIO\fR should be an
integer ratio such as "24000:1001" (23.976fps), "30000:1001" (29.97fps), or
"25:1" (25fps). This option is temporary, and may disappear in future
releases. (Hint: To convert a decimal like 23.976 to an integer ratio, just
multiply by 1000, i.e. 23976:1000)

.SS Audio stream options
.TP
\fB\-normalize\fR
Normalize the volume of the audio. Useful if the audio is too quiet or too
loud, or you want to make volume consistent for a bunch of videos.

.TP
\fB\-abitrate\fR \fINUM\fR
Encode audio at \fINUM\fR kilobits per second.  Reasonable values include
128, 224, and 384. The default is 224 kbits/sec, good enough for most
encodings. The value must be within the allowable range for the chosen disc
format; Ignored for VCD, which must be 224.

.TP
\fB\-nowav\fR
Skip the intermediate .wav\-ripping step, and encode the audio stream
directly with ffmpeg (this may cure some audio encoding or sync problems).

===Other options===

.TP
\fB\-config\fR \fIFILE\fR
Read configuration from \fIFILE\fR, containing 'tovid' alone on the first
line, and free\-formatted (whitespace\-separated) tovid command\-line options
on remaining lines.

.TP
\fB\-debug\fR
Print extra debugging information to the log file. Useful in diagnosing
problems if they occur. This option also leaves the log file (with a .log
extension) in the directory after encoding finishes.

.TP
\fB\-force\fR
Force encoding of already\-compliant video or audio streams.

.TP
\fB\-overwrite\fR
Overwrite any existing output files (with the same name as the given
\fB\-out\fR option).

.TP
\fB\-fake\fR
Do not actually encode; only print the commands (mplayer, mpeg2enc etc.)
that would be executed. Useful in debugging; have tovid give you the
commands, and run them manually.

.TP
\fB\-priority\fR {low|medium|high}
Sets the main encoding process to the given priority. With high priority,
it may take other programs longer to load and respond. With lower priority,
other programs will be more responsive, but encoding may take 30\-40%
longer.  The default is high priority.

.TP
\fB\-discsize\fR \fINUM\fR
Sets the desired target DVD/CD\-R size to \fINUM\fR MB (10^6).  Default is 700
for CD, 4500 for DVD. Use higher values at your own risk. Use 650 or lower
if you plan to burn to smaller\-capacity CDs.

.TP
\fB\-parallel\fR
Will perform encode/rip processes in parallel using named pipes. Maximizes
CPU utilization and minimizes disk usage.

.TP
\fB\-update\fR \fISECS\fR
Print status updates at intervals of \fISECS\fR seconds. This affects how
regularly the progress\-meter is updated. The default is once per second

.TP
\fB\-mplayeropts\fR \fB"\fR\fIOPTIONS\fR\fB"\fR
Append \fIOPTIONS\fR to the mplayer command run during video encoding.  Use
this if you want to add specific video filters (documented in the mplayer
manual page). Overriding some options will cause encoding to fail, so use
this with caution!

.TP
\fB\-ffmpeg\fR (EXPERIMENTAL)
Use ffmpeg for video encoding, instead of mplayer/mpeg2enc.  Encoding will
be noticeably faster; (S)VCD and DVD are supported, but KVCD/KDVD is not
fully supported yet.

.TP
\fB\-nofifo\fR (EXPERIMENTAL)
Do not use a FIFO pipe for video encoding. If you are getting "Broken pipe"
errors with normal encoding, try this option.  WARNING: This uses lots of
disk space (about 2 GB per minute of video).

.TP
\fB\-keepfiles\fR
Keep the intermediate files after encoding. Usually, this means the audio
and video streams are kept (eg the .ac3 and .m2v files for an NTSC DVD).
This doesn't work with \-parallel because the intermediate files are named
pipes, and not real files.

.TP
\fB\-quiet\fR
Reduce output to the console.

.SS See also
.P
\fBdvrequant\fR(1), \fBidvid\fR(1), \fBmakedvd\fR(1), \fBmakemenu\fR(1),
\fBmakeslides\fR(1), \fBmakexml\fR(1), \fBpostproc\fR(1), \fBtovid\fR(1)

.SS Contact
.P
For further assistance, contact information, forum and IRC links,
please refer to the tovid homepage (http://tovid.org/).


.\" man code generated by txt2tags 2.3 (http://txt2tags.sf.net)
.\" cmdline: txt2tags -t man -i /home/friedrij/dev/tovid-svn/trunk/tovid/docs/src/en/tovid.t2t -o /home/friedrij/dev/tovid-svn/trunk/tovid/docs/man/tovid.1

