#! /bin/bash
# Do a "quick release" of the SVN code

TARGET_DIR="/home/groups/t/to/tovid/htdocs/download"

if test $# -lt 1; then
    echo "Usage: quickrelease USERNAME"
    exit
else
    USERNAME=$1
fi
./bootstrap
./configure
make dist
scp tovid-svn*.tar.gz $USERNAME@shell.sourceforge.net:$TARGET_DIR
rm -i tovid-svn*.tar.gz

