#!/bin/bash

# post-Docbook-to-HTML cleanup script

# Rename index.html to toc.html
# Rename ch01.html to index.html
# Fix all references to point to the new files

mv index.html toc.html
mv ch01.html index.html
for file in *.html; do
    cat $file | sed -e 's/index\.html/toc.html/g' -e 's/ch01\.html/index.html/g' > $file.new
    mv $file.new $file
done

# Remove TOC in index.html (will be the main tovid homepage)
cat index.html | sed '/<div class="toc">/,/<\/div>/d' > index.new.html
mv index.new.html index.html

#for i in fr es
#do
#  cp $i/index.html index.$i.html
#done

