#!/bin/bash

# Call this script after editing configure.ac or Makefile.am

# Copyright (C) 2005 Joe Friedrichsen <friedrij@users.berlios.de>
# 
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation; either 
# version 2 of the License, or (at your option) any later 
# version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# Test for good automake -- the no AM_PYTHON error
# tovid needs automake 1.10
AM_VERSION=$(automake --version | head -n 1 | sed 's/[a-zA-Z ()]//g')
AM_110=$(type -a automake-1.10 2>>/dev/null | awk '{print $3}')

if test "$AM_VERSION" == "1.10"; then
    AUTOMAKE=automake
elif test -n "$AM_110"; then
    AUTOMAKE=automake-1.10
else
    echo "I couldn't find automake-1.10 on your system. Is it installed?"
    echo "I need automake-1.10 to generate ./configure..."
    echo "Exiting..."
    exit 1
fi

# See if tovid has been installed previously
if test -e Makefile; then
    echo "I found a Makefile! This may mean you have a previous version"
    echo "of tovid installed. Old tovid installations can cause strange"
    echo "and frustrating behavior. Do you want to uninstall it before"
    echo "continuing?"
    echo 
    echo -n "  Uninstall tovid? [y/N] "
    
    ANSWER=n
    read ANSWER
    
    if test "x$ANSWER" == "xy" || test "x$ANSWER" == "xY"; then
        echo -n "  Enter your root "
        su -c "make uninstall"
    fi      
    
    make distclean
fi

# Clean out old autotools-genreated files
rm -rvf "autom4te.cache"
rm -rvf aclocal.m4 config.log config.status configure Makefile Makefile.in

if aclocal \
   && $AUTOMAKE --gnu --add-missing \
   && autoconf
then
   echo
   echo "Done. You may now do ./configure && su -c \"make install\""
   echo
else
   echo "Uf. Autotools error. Read above for clues."
   exit 1
fi

exit 0

