#!/bin/sh

WKG_DIR=`pwd`

echo "Running aclocal, automake, and autoconf..."
./bootstrap && ./configure

echo "Refreshing the man pages..."
cd docs
if ./docmake.py; then :
else
   echo "Uf. Couldn't make the new manpages. Read above for clues."
   exit 1
fi
cd $WKG_DIR

echo "Making distribution .tar.gz..."
make dist

echo "Checking the distribution..."
if make distcheck
then 
    echo "Great! You now a shiny new tarball"
else 
    echo "Uf. Problem checking the tarball. Read above for clues."
    exit 1
fi

exit 0