#! /bin/bash
# Do a "quick release" of the SVN code

if test $# -lt 1; then
    echo "quickrelease: Create and upload a tovid 'quick release' (SVN .tar.gz)"
    echo "Usage:"
    echo "    quickrelease USERNAME"
    echo "where USERNAME is your Google (GMail) username."
    echo "Warning: This script removes any existing quick-releases"
    echo "in the current directory (rm -f tovid-svn*.tar.gz)"
    exit
else
    USERNAME=$1
fi

# Make sure there are no commits (otherwise revision number
# will be wrong)
if $(svn stat -u | grep -q '^M'); then
    echo "You have uncommitted changes. Please run svn commit first."
    exit
fi

./bootstrap
./configure
rm -f tovid-svn*.tar.gz
make dist
TARBALL=$(ls -1 ./tovid-svn*.tar.gz)
./googlecode_upload.py \
    -s "quick-release" \
    -p tovid \
    -u $USERNAME \
    $TARBALL
rm -i tovid-svn*.tar.gz
