#! /usr/bin/env python
# todisc.py

# Get supporting classes from libtovid.metagui
from metagui import *

### --------------------------------------------------------------------
### Panels
### --------------------------------------------------------------------

# Control(option, label, default, help, ...)
files = FileList('-files',
    'Video files', None,
    'Video files to include on the disc')
titles = TextList('-titles',
    'Video titles', None,
    'Titles for each video',
    pull=files)

background = Filename('-background',
    'Background image or video', '',
    'Image or video file to display in the background of the main menu',
    'load', 'Select an image or video file')
bgaudio = Filename('-bgaudio',
    'Background audio', '',
    'Audio file to play while the main menu is showing',
    'load', 'Select an audio file', pull=background)

main = Panel("Main",
    Text('-menu-title',
        'Menu title', 'My video collection',
        'Title text displayed on the main menu'),
    
    HPanel("Files and titles", files, titles),

    background,
    bgaudio,
    
    Choice('-format',
        'Disc format', 'DVD',
        'Format of disc to create; SVCD can be burned to a CD-R',
        'DVD|SVCD'),
    Choice('-tvsys',
        'TV system', 'NTSC',
        'Standard TV system to use',
        'NTSC|PAL'),
    Flag('-static',
        'Static menus', False,
        'Create still-image menus; takes less time'),
    Flag('-submenus',
        'Create Submenus', False,
        'Create a submenu for each video title; takes more time'),
    Filename('-out',
        'Output name', '',
        'Name to use for the output directory where the disc will be created.',
        'save', 'Choose an output name')
)

general = Panel("General",
    FlagGroup('Menu style', 'exclusive',
        Flag('none', "Default: Thumbnail grid", True,
             "Centered grid of thumbnails, filling all available space"),
        Flag('-showcase', "Showcase: Large central image or video", False,
             "Showcase an image or video in a large central frame"),
        Flag('-textmenu', "Textmenu: Text on a background", False,
             "Text-only menu, with image or video background")
        ),
    Filename('-showcase',
        'Showcase', '',
        'Image or video file to be showcased in a large central frame',
        'load', 'Select an image or video file.'),
    Filename('-background',
        'Background', '',
        'Image or video displayed in the background of the main menu',
        'load', 'Select an image or video file'),
    Filename('-bgaudio',
        'Audio', '',
        'Audio file played while the main menu is showing',
        'load', 'Select an audio file'),
    Flag('-submenus',
        'Create submenus', False),
    Flag('-static',
        'Static menus (takes less time)', False),
    Text('-menu-title',
        'Menu title', '',
        'Title of the main menu'),
    Number('-menu-length',
        'Menu length', 30,
        'Duration of menu in seconds',
        0, 120, 'scale'),
    Flag('-keep-files',
        'Keep useful intermediate files on exit', False),
    Flag('-no-ask',
        'No prompts for questions', False),
    Flag('-no-warn',
        'Do not pause at warnings', False),
    Flag('-use-makemenu',
        'Use makemenu', False,
        'Create menus using the makemenu script instead of todisc'),
    Text('-tovidopts',
        'Custom tovid options', '',
        "Space-separated list of options to pass to tovid for encoding.")
)

menu = Panel("Menu",
    Flag('-ani-submenus',
        'Animated submenus (takes more time)', False,
        'tooltip'),
    Flag('-menu-fade',
        'Fade in menu', False,
        'tooltip'),
    Panel("Seek times",
          List('-seek',
              'Seek time', '',
              'Play thumbnail videos from the given seek time (seconds)'),
          Number('-bgvideo-seek',
              'Background video seek time', 2,
              'Play background video from the given seek time (seconds)',
              0, 3600, 'scale'),
          Number('-bgaudio-seek',
              'Background audio seek time', 2,
              'Play background audio from the given seek time (seconds)',
              0, 3600, 'scale'),
          Number('-showcase-seek',
              'Showcase video seek time', 2,
              'Play showcase video from the given seek time (seconds)',
              0, 3600, 'scale')
    ),
    Choice('-align',
        'Montage alignment', 'north',
        'Controls positioning of the thumbnails and their titles',
        'north|south|east|west'),
    Filename('-intro',
        'Intro video', '',
        'Video to play before showing the main menu',
        'load', 'Select a video file'),
    Choice('-showcase-titles-align',
        'Video(s) title alignment', 'west',
        'tooltip',
        'west|east|center'),
    Choice('-showcase-framestyle',
        'Showcase frame style', 'none',
        'tooltip',
        'none|glass'),
    Text('-showcase-geo',
        'Showcase image position (XxY', '',
        'tooltip')
)

thumbnails = Panel("Thumbnails",
    Flag('-3dthumbs',
        'Create 3D thumbs', False,
        'tooltip'),
    Choice('-thumb-shape',
        'Thumb shape', 'normal',
        'tooltip',
        'normal|oval|plectrum|egg'),
    Number('-opacity',
        'Thumbnail opacity', 100,
        'tooltip',
        1, 100, 'spin'),
    Number('-blur',
        'Blur', 4,
        'tooltip',
        1, 5, 'spin'),
    List('-rotate-thumbs',
        'Rotate Thumbs (list)', '',
        'tooltip'),
    Text('-wave',
        'Wave effect for showcase thumb', 'default',
        'tooltip'),
    Number('-rotate',
        'Rotate Showcase thumb', 5,
        'tooltip',
        -30, 30, 'spin'),
    Color('-thumb-mist-color',
        'Thumb mist color', 'white',
        'tooltip'),
    Flag('-tile3x1',
        'Arrange thumb montage in 1 row of 3 thumbs', False,
        'tooltip')
)


audio = Panel("Audio",
    Number('-menu-audio-length',
        'Menu audio length', 30,
        'tooltip',
        0, 120, 'scale'),
    Number('-menu-audio-fade',
        'Menu audio fade', 1,
        'tooltip',
        0, 10, 'scale'),
    Filename('-submenu-audio',
        'Submenu audio file', '',
        'tooltip',
        'load', 'Select an audio file, or video file with audio'),
    Number('-submenu-audio-length',
        'Submenu audio length', 30,
        'tooltip',
        0, 120, 'scale'),
    Number('-submenu-audio-fade',
        'Submenu audio fade', 1,
        'tooltip',
        0, 10, 'scale')
)


text = Panel("Text/Font",
    Font('-menu-font',
        'Menu title font', 'Helvetica',
        'tooltip'),
    Font('-thumb-font',
        'Video title(s) font', 'Helvetica',
        'tooltip'),
    Number('-menu-fontsize',
        'Menu title font size', 20,
        'tooltip',
        0, 80, 'scale'),
    Number('-thumb-fontsize',
        'Video title(s) font size', 12,
        'tooltip',
        0, 80, 'scale'),
    Color('-title-color',
        'Title color', '',
        'tooltip'),
    Color('-submenu-title-color',
        'Submenu title color', '',
        'tooltip'),
    Color('-thumb-text-color',
        'Video title(s) color', '',
        'tooltip'),
    Panel("Mist",
          Flag('-text-mist',
              'Text mist', False,
              'tooltip'),
          Panel("Nesting is fun",
                Color('-text-mist-color',
                    'Text mist color', '',
                    'tooltip'),
                Number('-text-mist-opacity',
                    'Text mist opacity', 60,
                    'tooltip',
                    1, 100, 'spin')
          ),
    ),
    Choice('-menu-title-geo',
        'Menu title position', 'south',
        'tooltip',
        'north|south|west|east|center'),
    Text('-menu-title-offset',
        'Offset for menu title position', '+0+0',
        'tooltip'),
    Color('-stroke-color',
        'Stroke color', '',
        'tooltip'),
    Color('-submenu-stroke-color',
        'Submenu stroke color', '',
        'tooltip'),
    Number('-title-gap',
        'Space between Textmenu titles (pixels)', 2,
        'tooltip',
        0, 400, 'spin'),
    Number('-text-start',
        'Start Textmenu titles at: (pixels)', 2,
        'tooltip',
        0, 460, 'spin')
)

authoring = Panel("Authoring",
    List('-chapters',
        'Number of Chapters', '',
        'Single value or list'),
    List('-chain-videos',
        'Chain videos together', '',
        'See "man todisc" for details'),
    Choice('-widescreen',
        'Widescreen', None,
        'tooltip',
        'nopanscan|noletterbox'),
    Choice('-aspect',
        'Aspect ratio', '4:3',
        'tooltip',
        '4:3|16:9'),
    Color('-highlight-color',
        'Highlight color', '',
        'tooltip'),
    Color('-select-color',
        'Selection color', '',
        'tooltip'),
    Choice('-button-style',
        'Button style', 'rect',
        'tooltip',
        'rect|text|text-rect'),
    List('-audio-lang',
        'Default audio language', '',
        'Single value or list'),
    List('-subtitles',
        'Default subtitle language', '',
        'Single value or list'),
    Number('-outlinewidth',
        'Outlinewidth for spumux buttons', 4,
        'tooltip',
        0, 20, 'scale'),
    Number('-loop',
        'Loop', 10,
        'tooltip',
        0, 30, 'scale'),
    Flag('-playall',
        '"Play all" button', False,
        'tooltip')
)


### --------------------------------------------------------------------
### Application and GUI
### --------------------------------------------------------------------

style = Style(bgcolor='white', font=('Helvetica', 12, 'bold'))

todisc = Application('todisc',
    [main, general, menu, thumbnails, audio, text, authoring])
gui = GUI("todiscgui", [todisc])
gui.run()

