#!/bin/bash
# This script converts the tovid DocBook documentation
# into XHTML format, and prepares it for web distribution

echo "Doing the English translation"
xmlto -m tovid_html.xsl html tovid_documentation.xml
xmlto -o download -m tovid_html.xsl html-nochunks tovid_documentation.xml

echo "Running HTML tidy on English translation"
tidy -i -m *.html > /dev/null 2>&1
tidy -i -m download/tovid_documentation.html > /dev/null 2>&1

for i in fr es
do
    echo "Doing the $i translation"
    xmlto -o $i -m tovid_html.xsl html $i/tovid_documentation.$i.xml
    xmlto -o download -m tovid_html.xsl html-nochunks $i/tovid_documentation.$i.xml

    echo "Running HTML tidy on $i"
    tidy -utf8 -i -m $i/*.html > /dev/null 2>&1
done

# tidy all the HTML in ./download
tidy -utf8 -i -m download/*.html > /dev/null 2>&1

