#! /usr/bin/env python2.4
# pyidvid

import sys
import os

import libtovid
from libtovid.filetypes import MultimediaFile

# ===========================================================
# Execution begins here
#
# This stuff is just for testing; the true pyidvid script will
# do real argument-parsing and whatnot.
# ===========================================================
if __name__ == '__main__':
    # If no arguments were provided, print usage notes
    if len(sys.argv) == 1:
        print "Usage: %s FILE" % sys.argv[0]
    else:
        print "Creating a MultimediaFile object from file: %s" % sys.argv[1]
        infile = MultimediaFile(sys.argv[1])
        infile.display()
