#! /usr/bin/env python
# tktovid

"""A Tkinter graphical user interface for tovid. Highly experimental."""

"""Note on notation:
tkinter widgets variable names shall use a prefix describing widget type, and
camel-case for remaining words, i.e.

    fra: Frame
    mnu: Menu
    lbl: Label
    btn: Button
    ent: Entry
    lst: Listbox
    chk: Checkbox
    rb:  Radiobutton
    var: Control variables (Variable, StringVar, IntVar, DoubleVar)

"""

from Tkinter import *
from tkFileDialog import *

# ============================
#
# Frames for grouping controls
#
# ============================

class FormatFrame(Frame):
    """A frame containing controls suitable for setting disc format
    (VCD, SVCD, DVD, etc.)"""
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.rbFormat = {}            # Radiobuttons, indexed by format name
        self.varFormat = StringVar()  # Currently selected format
        self.grid()    
        self.drawWidgets()

    def drawWidgets(self):
        # Label
        self.lbl = Label(self, text="Disc format:")
        self.lbl.pack(side=LEFT)
        # Radio buttons
        for format in ['DVD', 'VCD', 'SVCD']:
            self.rbFormat[format] =\
                Radiobutton(self,
                            text = format,
                            value = format,
                            variable = self.varFormat,
                            command = self.changeFormat)
            self.rbFormat[format].pack(side=LEFT)
        self.varFormat.set('DVD')
        
    def changeFormat(self):
        """Event handler called when format radio buttons are clicked."""
        print "Disc format: %s" % self.varFormat.get()
        
    def getOptions(self):        
        return " -%s" % str(self.varFormat.get()).lower()


class TvsysFrame(Frame):
    """A frame containing controls suitable for setting TV system (PAL, NTSC).
    """
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.rbTvsys = {}         # Radiobuttons, indexed by tvsys name
        self.varTvsys = StringVar()  # Currently selected tvsys
        self.grid()
        self.drawWidgets()

    def drawWidgets(self):
        # Label
        self.label = Label(self, text="TV system:")
        self.label.pack(side=LEFT)
        # Radio buttons
        for tvsys in ['NTSC', 'PAL']:
            self.rbTvsys[tvsys] =\
                Radiobutton(self,
                            text = tvsys,
                            value = tvsys,
                            variable = self.varTvsys,
                            command = self.changeTvsys)
            self.rbTvsys[tvsys].pack(side=LEFT)
        self.varTvsys.set('NTSC')
    
    def changeTvsys(self):
        """Event handler called when TV system radio buttons are clicked."""
        print "TV system: %s" % self.varTvsys.get()
        
    def getOptions(self):
        return " -%s" % str(self.varTvsys.get()).lower()



class FileListFrame(Frame):
    """A frame containing a list of filenames, and controls to add or delete
    files from the list.
    """
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.curtitle = StringVar()  # Text of the currently selected title
        self.files = Variable()      # List of current files
        self.titles = Variable()     # List of current titles
        self.curindex = 0
        self.grid()
        self.drawWidgets()

    def drawWidgets(self):
        # List box and add/remove buttons
        self.lblFiles = Label(self, text="Files")
        self.lblFiles.grid(row=0, column=0, columnspan=2, sticky=W)
        self.lstFiles = Listbox(self, width=30, selectmode=EXTENDED,
                                 listvariable=self.files)
        self.lstFiles.grid(row=1, column=0, columnspan=2)
        self.btnAdd = Button(self, text="Add...", command=self.addFiles)
        self.btnAdd.grid(row=2, column=0, sticky=E+W)
        self.btnDelete = Button(self, text="Remove",
                                   command=self.deleteFiles)
        self.btnDelete.grid(row=2, column=1, sticky=E+W)
        # Title list box
        self.lblTitles = Label(self, text="Titles")
        self.lblTitles.grid(row=0, column=3, sticky=W)
        self.lstTitles = Listbox(self, width=30, listvariable=self.titles)
        self.lstTitles.bind('<ButtonRelease-1>', self.selectTitle)
        self.lstTitles.grid(row=1, column=3)
        self.entTitle = Entry(self, width=30, textvariable=self.curtitle)
        self.entTitle.bind('<Return>', self.setTitle)
        self.entTitle.grid(row=2, column=3)

    def selectTitle(self, event=None):
        """Event handler when a title in the title list is selected."""
        selected = self.lstTitles.curselection()
        if len(selected) > 0:
            self.curindex = selected[0]
            self.curtitle.set(self.lstTitles.get(self.curindex))

    def setTitle(self, event=None):
        """Event handler when Enter is pressed after editing a title."""
        newtitle = self.curtitle.get()
        print "Setting title to '%s'" % newtitle
        self.lstTitles.delete(self.curindex)
        self.lstTitles.insert(self.curindex, newtitle)
        
    def addFiles(self):
        """Event handler for adding files to the list box"""
        files = askopenfilenames(parent=self, title='Add files')
        for file in files:
            print "Adding '%s' to the file list" % file
            self.lstFiles.insert(END, file)
            # Add a dummy title (with pathname removed)
            title = file.split('/')[-1]
            self.lstTitles.insert(END, title)

    def deleteFiles(self):
        """Event handler for deleting files from the list box"""
        selection = self.lstFiles.curselection()
        # Using reverse order prevents reflow from messing up indexing
        for line in reversed(selection):
            print "Removing '%s' from the file list" % self.lstFiles.get(line)
            self.lstFiles.delete(line)
            self.lstTitles.delete(line)

    def getOptions(self):
        return " -files '%s' -titles '%s'" % \
             ("' '".join(self.files.get()), "' '".join(self.titles.get()))


class BackgroundsFrame(Frame):
    """Widgets for setting background image, video and audio"""
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.varImage = StringVar()
        self.varVideo = StringVar()
        self.varAudio = StringVar()
        self.grid()
        self.drawWidgets()
    
    def drawWidgets(self):
        self.lblHeading = Label(self, text="Menu backgrounds")
        self.lblHeading.pack(side=TOP, anchor=W)
        # BG image
        fraImage = Frame(self)
        self.lblImage = Label(fraImage, text="BG image")
        self.lblImage.pack(side=LEFT)
        self.entImage = Entry(fraImage, width=30, textvariable=self.varImage)
        self.entImage.pack(side=LEFT)
        self.btnImage = Button(fraImage, text="Browse...",
                               command=self.browseImage)
        self.btnImage.pack(side=LEFT)
        fraImage.pack(side=TOP)
        # BG video
        fraVideo = Frame(self)
        self.lblVideo = Label(fraVideo, text="BG video")
        self.lblVideo.pack(side=LEFT)
        self.entVideo = Entry(fraVideo, width=30, textvariable=self.varVideo)
        self.entVideo.pack(side=LEFT)
        self.btnVideo = Button(fraVideo, text="Browse...",
                               command=self.browseVideo)
        self.btnVideo.pack(side=LEFT)
        fraVideo.pack(side=TOP)
        # BG audio
        fraAudio = Frame(self)
        self.lblAudio = Label(fraAudio, text="BG audio")
        self.lblAudio.pack(side=LEFT)
        self.entAudio = Entry(fraAudio, width=30, textvariable=self.varAudio)
        self.entAudio.pack(side=LEFT)
        self.btnAudio = Button(fraAudio, text="Browse...",
                               command=self.browseAudio)
        self.btnAudio.pack(side=LEFT)
        fraAudio.pack(side=TOP)

    def browseImage(self):
        filename = askopenfilename(parent=self, title="Select image file")
        print "Background image: %s" % filename
        self.varImage.set(filename)

    def browseVideo(self):
        filename = askopenfilename(parent=self, title="Select video file")
        print "Background video: %s" % filename
        self.varVideo.set(filename)

    def browseAudio(self):
        filename = askopenfilename(parent=self, title="Select audio file")
        print "Background audio: %s" % filename
        self.varAudio.set(filename)
    
    def getOptions(self):
        opts = ""
        if self.varImage.get():
            opts += " -bgimage '%s'" % self.varImage.get()
        if self.varVideo.get():
            opts += " -bgvideo '%s'" % self.varVideo.get()
        if self.varAudio.get():
            opts += " -bgvideo '%s'" % self.varAudio.get()
        return opts


class OutfileFrame(Frame):
    """A frame containing an output-file text entry/browser box."""
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.filename = StringVar() # Current output filename
        self.grid()
        self.drawWidgets()
    
    def drawWidgets(self):
        self.lblOutfile = Label(self, text="Output file:")
        self.lblOutfile.pack(side=LEFT)
        self.entOutfile = Entry(self, width=40, textvariable=self.filename)
        self.entOutfile.pack(side=LEFT)
        self.btnBrowse = Button(self, text="Browse...", command=self.onBrowse)
        self.btnBrowse.pack(side=LEFT)
        
    def onBrowse(self):
        filename = asksaveasfilename(parent=self, title="Select output file")
        print "Output file: %s" % filename
        self.filename.set(filename)

    def getOptions(self):
        return " -out '%s'" % self.filename.get()


# ============================
#
# Main application window
#
# ============================

class Application(Frame):
    def __init__(self, master=None):
        Frame.__init__(self, master)
        self.grid()
        self.drawWidgets()
        
    def drawWidgets(self):
        self.filelist = FileListFrame(self)
        self.filelist.pack(side=TOP)

        self.format = FormatFrame(self)
        self.format.pack(side=TOP, anchor=W)

        self.tvsys = TvsysFrame(self)
        self.tvsys.pack(side=TOP, anchor=W)

        self.backgrounds = BackgroundsFrame(self)
        self.backgrounds.pack(side=TOP, anchor=W)

        self.outfile = OutfileFrame(self)
        self.outfile.pack(side=TOP, anchor=W)

        self.btnCommand = Button(self, text="Print command",
                                    command=self.showCommand)
        self.btnCommand.pack()
        self.btnQuit = Button(self, text="Quit", command=self.quit)
        self.btnQuit.pack()

    def showCommand(self):
        cmd = "todisc "
        cmd += self.filelist.getOptions()
        cmd += self.format.getOptions()
        cmd += self.tvsys.getOptions()
        cmd += self.backgrounds.getOptions()
        cmd += self.outfile.getOptions()
        print cmd

# ============================
#
# Entry point
#
# ============================

if __name__ == '__main__':
    app = Application()
    app.master.title("tktovid")
    app.mainloop()
