#! /usr/bin/env python
# todiscgui

"""A GUI for the todisc command-line program.

Usage:

    $ todiscgui

This GUI is written using the 'metagui' module from libtovid, a high-level
GUI design language that involves very little code.

See the wiki page about metagui for more details:

    http://tovid.wikia.com/wiki/Metagui

"""

# Get supporting classes from libtovid.metagui
from libtovid.metagui import *

### --------------------------------------------------------------------
### -files and -titles
### --------------------------------------------------------------------

"""todisc's -files and -titles options have a one-to-one correspondence.
Rather than make the user manually enter a title for each file, this
approach uses two lists, with one "dependent" on another via a filter.

Specifically, when the GUI user adds to -files, the corresponding
-titles should be automatically filled in with the filename, minus
pathname and extension.

In other words:
"""

import os
def to_title(filename):
    basename = os.path.basename(filename)
    firstdot = basename.find('.')
    return basename[0:firstdot]

files = FileList('-files',
    'Video files', None,
    'Video files to include on the disc',
    required=True)

titles = TextList('-titles',
    'Video titles', None,
    'Titles for each video',
    pull=files, # -titles is updated when -files is updated
    filter=to_title, # strip pathname and extension from filenames
    required=True)


### --------------------------------------------------------------------
### Main todisc options
### --------------------------------------------------------------------

main = Panel("Main",
    Text('-menu-title',
        'Menu title', 'My video collection',
        'Title text displayed on the main menu'),
    
    HPanel("Files and titles", files, titles),

    HPanel('',
        FlagGroup('Format', 'exclusive',
            Flag('-dvd', "DVD", True),
            Flag('-svcd', "SVCD", False)),
        FlagGroup('TV System', 'exclusive',
            Flag('-ntsc', "NTSC", True),
            Flag('-pal', "PAL", False))
        ),

    FlagGroup('Menu Style', '',
        Flag('-showcase', "Showcase style menu", False,
            "Arrange menu links along the outside edges, to leave room for" \
            " an optional 'showcase' image or video.",
            enables=Filename('',
               'Showcase', '',
               'Image or video file to be showcased in a large central frame',
               'load', 'Select an image or video file.')
        ),
        Flag('-textmenu', "Use text menu links (no thumbnails)", False,
            'Showcase style text only menu.  Optionally use a "showcase" ' \
            'image/video, or static/animated background.  See also ' \
            'quick-menu and switched menu in the "Menu" tab',
            enables=Number('',
                'Titles per column', 13,
                'Maximum number of titles per column',
                1, 50)
        )
    ),
    VPanel('Menu backgrounds',
          Filename('-background',
              'Image or video', '',
              'Graphic to display in the background of the main menu',
              'load', 'Select an image or video file'),
          Filename('-bgaudio',
              'Audio', '',
              'Audio file to play while the main menu is showing.  ' \
              'If static menu, default is to use audio length of 20 seconds.  ' \
              'Change with "Menu length" on "Menu" tab.',
              'load', 'Select an audio file')
    ),

    VPanel('Animation and submenus',
    Flag('-static',
        'Static menus', False,
        'Create still-image menus; takes less time.  ' \
        'For duration of background audio for static '
        'menus, use "menu length" on the "Menu" tab'),
    Flag('-submenus',
        'Create Submenus', False,
        'Create a submenu for each video title; takes more time.'),
    Flag('-ani-submenus',
        'Animated submenus (takes more time)', False,
        'Create an animated submenu for each video.  ' \
        'Submenu links lead to chapter points.')
    ),

    List('',
        'Custom todisc options', '',
        'Space-separated list of custom options to pass to todisc.'),
    Filename('-out',
        'Output name', '',
        'Name to use for the output directory where the disc will be created.',
        'save', 'Choose an output name',
        required=True)
)

general = Panel("General",
    Flag('-keep-files',
        'Keep useful intermediate files on exit', False),
    Flag('-no-ask',
        'No prompts for questions', False),
    Flag('-no-warn',
        'Do not pause at warnings', False),
    Flag('-use-makemenu',
        'Use makemenu', False,
        'Create menus using the makemenu script instead of todisc'),
    Text('-tovidopts',
        'Custom tovid options', '',
        "Space-separated list of options to pass to tovid for encoding.")
)

menu = Panel("Menu",
    Number('-menu-length',
        'Menu length', 20,
        'Duration of menu in seconds',
        0, 120, 'scale'),
    Flag('-menu-fade',
        'Fade in menu', False,
        'Fade  the  menu  in  and out The background ' \
        ' will fade in first, then title ' \
        '(and mist if called for), then the menu thumbs.  ' \
        'The fadeout is in reverse order'),
    Flag('-quick-menu', "Make a quick animated showcase style menu.  ", False,
        'Ten times faster than normal showcase animation.  ' \
        'A showcase image is required.  No video thumbs are made.  '
        'Not compatible with wave or rotate options'),
    Flag('-switched-menus', "Make switched menus", False,
        "This will make a showcase style menu with text menu links.  " \
        "The showcased VIDEO or IMAGE will be of each video 'title' " \
        " in the menu.  Do not select showcase or a showcase file for this option.   " \
        "Use with quick menu option above for a huge speed up !"),
    Panel("Seek times",
          List('-seek',
              'Seek time', '',
              'Play thumbnail videos from the given seek time (seconds).  ' \
              'A single value or space separated list, one value per video.  ' \
              'Also used for seeking in switched menus.'),
          Number('-bgvideo-seek',
              'Background video seek time', 2,
              'Play background video from the given seek time (seconds)',
              0, 3600, 'scale'),
          Number('-bgaudio-seek',
              'Background audio seek time', 2,
              'Play background audio from the given seek time (seconds)',
              0, 3600, 'scale'),
          Number('-showcase-seek',
              'Showcase video seek time', 2,
              'Play showcase video from the given seek time (seconds).  '
              'Note: switched menus use the value(s) from "Seek time" option above, '
              'not this one',
              0, 3600, 'scale')
    ),
    Choice('-align',
        'Montage alignment', 'north',
        'Controls positioning of the thumbnails and their titles',
        'north|south|east|west|center'),
    Filename('-intro',
        'Intro video', '',
        'Video to play before showing the main menu',
        'load', 'Select a video file'),
    Choice('-showcase-titles-align',
        'Video(s) title alignment', 'west',
        'This is a showcase style only option.  The default is to center ' \
        'the text above the thumbnails.  This option will align the titles ' \
        ' either to the left (west) or right (east).',
        'west|east|center'),
    Choice('-showcase-framestyle',
        'Showcase frame style', 'none',
        'This is a showcase style only option.  The "none" option will use the ' \
        'default frame method, using imagemagick. The "glass" option ' \
        'will use mplayer to make frames, giving an animated effect.  The ' \
        'glass style can be much faster - especially if used without -rotate and -wave options',
        'none|glass'),
    Text('-showcase-geo',
        'Showcase image position (XxY)', '',
        'This is a showcase style only option. ' \
        'Enter the position of the top left corner of the showcase image: e.g. "200x80"')
)

thumbnails = Panel("Thumbnails",
    Flag('-3dthumbs',
        'Create 3D thumbs', False,
        'This will give an illusion of 3D to the thumbnails: ' \
        'dynamic lighting on rounded thumbs, and a  raised ' \
        ' effect on rectangular thumbs'),
    Choice('-thumb-shape',
        'Thumb shape', 'normal',
        'Apply a shaped transparency mask to thumbnail videos. ' \
        'Note: to disable the "mist" background ' \
        'behind each thumb, use "none" for -thumb-mist-color.',
        'normal|oval|plectrum|egg'),
    Number('-opacity',
        'Thumbnail opacity', 100,
        'Opacity  of thumbnail videos as a percentage ' \
        '(no percent sign).  Less than 100(%) ' \
        'is semi-transparent.  Not recommended with dark backgrounds.',
        1, 100, 'spin'),
    Number('-blur',
        'Blur', 4,
        'The amount of feather blur to apply to the thumb-shape.  ' \
        'Default is 4.0 which will more or less keep the shape, ' \
        'creating transparency at the edges.  Choose float or ' \
        'integer values between 0.1 and 5.0',
        1, 5, 'spin'),
    List('-rotate-thumbs',
        'Rotate Thumbs (list)', '',
        'Rotate  thumbs  the  given amount in degrees - can be positive ' \
        'or negative.  There must be one value for each file given with -files.  ' \
        'If the values are not the same distance from zero, the thumbs will be  ' \
        'of  different sizes as images are necessarily resized *after* rotating.'),
    Flag('-wave', 'Wave effect for showcase thumb', 'False',
        'Wave effect for showcase image|video.  Alters thumbs along a sine wave ' \
        'This will pass a wave arg of -20x556, which produces a gentle wave with a ' \
        'small amount of distortion.  To use other values you will need to use ' \
        'the "tovidopts" box on the first panel - see man todisc for details.'),
    Number('-rotate',
        'Rotate Showcase thumb', 0,
        'Rotate the showcase image|video clockwise by this number of degrees.',
        -30, 30, 'spin'),
    VPanel('Thumb mist',
    Flag('', "", False,
        "",
    enables=Color('-thumb-mist-color',
        'Thumb mist color', 'white',
        'Color of mist behind thumbnails (not a showcase option).')),
    Flag('-thumb-mist-color', "Transparent thumb mist", False,
        'Do not use a mist behind thumbs (not a showcase option).  ' \
        'Warning: this may cause contrast problems unless you use a large bold font')
),
    Flag('-tile3x1',
        'Arrange thumb montage in 1 row of 3 thumbs', False,
        'Use a montage tile of 3x1 instead of the usual 2x2 (for 3 videos only).')
)

audio = Panel("Audio",
    Number('-menu-audio-fade',
        'Menu audio fade', 1,
        'Number  of  sec to fade given menu audio in and out (default: 1.0 seconds) ' \
        'If you use -menu-audio-fade 0 then the audio will not be faded.',
        0, 10, 'scale'),
    List('-submenu-audio',
        'Submenu audio file', '',
        'Quoted list of files for sub-menu backgrounds. If one file is given, then it will ' \
        'be used for all sub-menus.  Else the number given must equal the number of ' \
        'chapters, though the keyword "none" may be used for silence.'),
    Number('-submenu-audio-length',
        'Submenu audio length', 30,
        'The length of the background audio for a static submenu.  ' \
        'The default is to use the full length of the supplied audio ( -bgaudio ).',
        0, 120, 'scale'),
    Number('-submenu-audio-fade',
        'Submenu audio fade', 1,
        'Number of sec to fade given sub-menu audio in and out (default: 1.0 seconds)',
        0, 10, 'scale')
)


text = Panel("Text/Font",
    Font('-menu-font',
        'Menu title font', 'Helvetica',
        'The font to use for the menu title'),
    Font('-thumb-font',
        'Video title(s) font', 'Helvetica',
        'The font to use for the video titles'),
    Number('-menu-fontsize',
        'Menu title font size', 20,
        'The font size to use for the menu title',
        0, 80, 'scale'),
    Number('-thumb-fontsize',
        'Video title(s) font size', 12,
        'The font size to use for the video titles',
        0, 80, 'scale'),
    Color('-title-color',
        'Title color', '',
        'The font color to use for the menu title'),
    Color('-submenu-title-color',
        'Submenu title color', '',
        'The font color to use for submenu title(s)'),
    Color('-thumb-text-color',
        'Video title(s) color', '',
        'The font color to use for the video titles'),
    Panel("Mist",
        Flag('-text-mist',
            'Text mist', False,
            'Use a "mist" behind the menu title (helps with contrast).'),
        Color('-text-mist-color',
            'Text mist color', '',
            'Color of the mist behind the menu title.'),
        Number('-text-mist-opacity',
            'Text mist opacity', 60,
            'The opacity of the mist behind the menu title.',
            1, 100, 'spin')
        ),
    Choice('-menu-title-geo',
        'Menu title position', 'south',
        'The position of the menu title',
        'north|south|west|east|center'),
    Text('-menu-title-offset',
        'Offset for menu title position', '+0+50',
        'Menu title position as an offset (in pixels) from "Menu title position" above.  '
        'Use +X+Y syntax.  This value is applied to the video *before* is is scaled.'),
    Color('-stroke-color',
        'Stroke color', '',
        'Outline color for the main menu font. Use "none" for transparent outline.'),
    Color('-submenu-stroke-color',
        'Submenu stroke color', '',
        'The color for the sub-menu font outline (stroke).'),
    Number('-title-gap',
        'Space between Textmenu titles (pixels)', 10,
        'Leave this much vertical gap between titles.  ' \
        'Default is 10 for line buttons, 15 for text-rect buttons.  ' \
        'This value is applied before the menu is scaled.',
        0, 400, 'spin'),
    Number('-text-start',
        'Start Textmenu titles at: (pixels)', 50,
        'The text menu will start a this pixel in the Y-axis (north/south).  ' \
        'This value is applied before the menu is scaled.',
        0, 460, 'spin'),
)

authoring = Panel("Authoring",
    List('-chapters',
        'Chapters', '',
        'Single value/string or list.  ' \
        'Can be an integer for "# of chapters", ' \
        'or a comma separated string of chapter points in HH:MM:SS format.  ' \
        'The first HH:MM:SS format chapter MUST be 00:00:00 '
        'If using grouped videos and HH:MM:SS format ' \
        'link grouped chapter points with a "+" separator.'),
    List('-chain-videos',
        'Chain videos together', '',
        'See "man todisc" for details'),
    Choice('-widescreen',
        'Widescreen', None,
        'This will output a <video widescreen=nopanscan /> tag (for example) ' \
        'for the dvdauthor xml file.  It will affect all videos in the titleset.  '
        'Use in conjunction with "Aspect ration" if your dvd player is cropping your videos',
        'nopanscan|noletterbox'),
    Choice('-aspect',
        'Aspect ratio', '4:3',
        'This will output a <video aspect WIDTH:HEIGHT /> tag for the dvdauthor xml file.  ' \
        'It will affect all videos in the titleset.',
        '4:3|16:9'),
    Color('-highlight-color',
        'Highlight color', '',
        'Color to use for the menu buttons that your dvd remote uses to navigate.'),
    Color('-select-color',
        'Selection color', '',
        'Color to use for the menu buttons that your dvd remote uses to select.'),
    Choice('-button-style',
        'Button style', 'rect',
        'Style or shape of the buttons that you will see when you play the DVD.  ' \
        '"rect" draws a rectangle around the thumbs, "text" uses the title text, ' \
        'and "text-rect" draws a rectangle around the title text.',
        'rect|text|text-rect'),
    List('-audio-lang',
        'Default audio language', '',
        'Single value or list'),
    List('-subtitles',
        'Default subtitle language', '',
        'Single value or list'),
    Number('-outlinewidth',
        'Outlinewidth for spumux buttons', 4,
        'For spumux outlinewidth variable.  This option may help if there is a large gap ' \
         'between words or characters in a text button, causing spumux to fail.',
        0, 20, 'scale'),
    Number('-loop',
        'Pause', 10,
        'Pause in seconds at end of menu.  Or use "Indefinate pause" item below.',
        0, 30, 'scale'),
    Flag('-loop',
        'Indefinite pause', False,
        'Pause indefinitely at the end of the menu.'),
    Flag('-playall',
        '"Play all" button', False,
        'Create a "Play All" button that lets you jump to the 1st title and play '
        'all the videos in sucession before returning to the main menu.')
)

burning = Panel("Burning",
    Flag('-burn',
        'Burn project on completion', False),
    Number('-speed',
        'Burning speed', 8,
        'Speed for burning',
        0, 30, 'scale'),
    Filename('-device',
        'Device to use for burning', '/dev/dvdrw',
        'Select or type your burning device (default: /dev/dvdrw)',
        'load', 'Select or type your burning device'),
)

### --------------------------------------------------------------------
### Application and GUI
### --------------------------------------------------------------------

todisc = Application('todisc',
    [main, general, menu, thumbnails, audio, text, authoring, burning])
gui = GUI("todiscgui", [todisc], 600, 800)
gui.run()

