#! /usr/bin/env python

# tovid GUI
# ===============
# A wxPython frontend for the tovid suite
#
# Project homepage: http://tovid.org/
#
# This software is licensed under the GNU General Public License
# For the full text of the GNU GPL, see:
#
#   http://www.gnu.org/copyleft/gpl.html
#
# No guarantees of any kind are associated with use of this software.
#
import wx
from libtovid.gui.frames import MainFrame

TovidGUI = wx.PySimpleApp()
#frame = TovidFrame(None, wx.ID_ANY, "tovid GUI")
#frame = MiniEditorFrame(None, wx.ID_ANY, "tovid GUI")
frame = MainFrame(None, wx.ID_ANY, "tovid GUI")
frame.Show(True)
TovidGUI.MainLoop()