.TH todiscgui "1" "February 2007" "tovid 0.30" "User commands"
.SH NAME
todiscgui
.SH SYNOPSIS
\fBtodiscgui\fR\

.SH DESCRIPTION
todiscgui is a GUI which can create video discs using a bunch of videos that you
provide. The GUI handles all the necessary conversion (using tovid), menu
creation, and disc authoring, and disc burning (using makevcd or makedvd).

.SH SEE ALSO
todisc(1), tovid(1), makevcd(1, makedvd(1)
.br
Tovid official documentation is located at: http://www.tovid.org/

.SH AUTHOR
Eric Pierce <wapcaplet99@yahoo.com>

This manual page was written for the Debian system by
Julien Valroff <julien@kirya.net> and
Joe Friedrichsen <pengi.films@gmail.com>.

.SH COPYRIGHT
Copyright Eric Pierce <wapcaplet99@yahoo.com>

You are free to distribute this software under the terms of
the GNU General Public License. This software comes with no warranty.
