#! /usr/bin/env python
# -*- coding: utf-8 -*-

"""Quick-and-dirty 'make' tool for building tovid documentation."""

import os, sys, glob
# Get TDL
import libtovid
from libtovid import TDL
# Get mypydoc
import mypydoc

# Directory containing .t2t doc sources
source_dir = os.path.realpath('src')
# Directory to save output in
dest_dir = os.path.realpath('html')
man_dir = os.path.realpath('man')
man_pages = ['tovid', 'idvid', 'makemenu', 'makedvd', \
    'makeslides', 'makexml', 'postproc']

# Subdirectories of source_dir containing translations to build
translation_subdirs = [ 'en', 'es' ]

def newer(source, target):
    """Return True if the source file is more recently modified than the
    target; False otherwise."""
    source_mod = os.path.getmtime(source)
    if os.path.exists(target):
        target_mod = os.path.getmtime(target)
    else:
        target_mod = 0

    return source_mod > target_mod

    
def generate_t2t_tarball():
    """Create tar/gzip of all t2t sources in the html/download directory."""
    print "Generating .tar.gz of all .t2t sources..."
    for lang in translation_subdirs:
        cmd = 'tar --exclude .svn -czvvf %s/download/tovid_t2t_%s.tar.gz src/%s' % \
                (dest_dir, lang, lang)
        os.system(cmd)


def generate_manpages():
    for manpage in man_pages:
        infile = '%s/en/%s.t2t' % (source_dir, manpage)
        outfile = '%s/%s.1' % (man_dir, manpage)
        if newer(infile, outfile):
            generate_manpage(infile, outfile)
        else:
            print "Skipping %s" % outfile

def generate_manpage(t2tfile, manfile):
    print "Generating manual page from %s" % t2tfile
    cmd = 'txt2tags -t man -i "%s" -o "%s"' % (t2tfile, manfile)
    os.system(cmd)


def generate_html(t2tfile, htmlfile):
    cmd = 'txt2tags -i %s -o %s' % (t2tfile, htmlfile)
    cmd += ' --encoding iso-8859-1'
    cmd += ' -t xhtml --css-sugar --toc --style=tovid_screen.css'
    # Run txt2tags cmd, displaying its normal output
    os.system(cmd)

    # Run tidy on HTML output
    #os.popen2("tidy -utf8 -i -m %s" % htmlfile)


def generate_pydocs():
    print "Generating HTML documentation of libtovid Python sources"
    for mod in libtovid.__all__:
        mod = "libtovid.%s" % mod
        print "Writing %s/pydocs/%s.html" % (dest_dir, mod)
        htmlfile = open("%s/pydocs/%s.html" % (dest_dir, mod), 'w')
        gen = mypydoc.HTMLGenerator()
        html = gen.document(mod)
        htmlfile.write(html)
        htmlfile.close()
        # Run tidy on HTML output
        #os.popen2("tidy -utf8 -i -m %s" % htmlfile)

    
def generate_tdl_t2t():
    """Generate t2t versions of the TDL documentation defined in TDL.py."""
    # For now, just generate a single file containing TDL usage notes
    t2t_str = "tovid design language\n\n\n" \
    + "==Disc==\n\n" \
    + "```\n" \
    + TDL.usage('Disc') \
    + "```\n\n" \
    + "==Menu==\n\n" \
    + "```\n" \
    + TDL.usage('Menu') \
    + "```\n\n" \
    + "==Video==\n\n" \
    + "```\n" \
    + TDL.usage('Video') \
    + "```\n\n"

    os.popen("rm -f %s/en/tdl.t2t" % source_dir)
    t2tfile = open('%s/en/tdl.t2t' % source_dir, 'w')
    t2tfile.write(t2t_str)
    t2tfile.close()


if __name__ == '__main__':

    print "tovid documentation maker"

    regen_all = False
    for arg in sys.argv[1:]:
        # Regenerate all HTML files
        if arg == 'all':
            regen_all = True
        # Generate manpages only (then exit)
        elif arg == 'man':
            generate_manpages()
            sys.exit()
        # Generate pydocs only (then exit)
        elif arg == 'pydocs':
            generate_pydocs()
            sys.exit()


    # Default: Generate HTML versions of all .t2t sources

    #generate_t2t_tarball()
    #generate_tdl_t2t()

    # Convert all language translations (.t2t sources) to HTML
    for trans_dir in translation_subdirs:
        print "Looking for .t2t sources in %s/%s" % (source_dir, trans_dir)
        for t2tfile in glob.glob('%s/%s/*.t2t' % (source_dir, trans_dir)):
            # Determine output path/filename
            # (Strip .t2t from basename and put in dest_dir/trans_dir)
            outfile = '%s/%s/%s.html' % \
                    (dest_dir, trans_dir, os.path.basename(t2tfile)[:-4])
            
            if regen_all:
                generate_html(t2tfile, outfile)
            else:
                # If the .t2t source is newer than the existing HTML target,
                # recreate the HTML.
                if newer(t2tfile, outfile):
                    print "Source file: %s is new. Regenerating %s" % \
                        (t2tfile, outfile)
                    generate_html(t2tfile, outfile)
                else:
                    print "Skipping file: %s" % t2tfile


    print "Done!"
