#! /bin/sh

# Call this script after editing configure.ac or Makefile.am
# then:
# $ ./configure
# $ make
# $ make install

# Copyright (C) 2005 Joe Friedrichsen <friedrij@users.berlios.de>
# 
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation; either 
# version 2 of the License, or (at your option) any later 
# version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

rm -rvf "autom4te.cache"
rm -rvf aclocal.m4 config.log config.status configure \
        Makefile Makefile.in setuplib.py
rm -rvf src/Makefile src/Makefile.in src/tovid-init.sh

aclocal \
&& automake --gnu --add-missing \
&& autoconf